modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="All rights reserved"

[[mods]] #mandatory
modId="oreplus" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ore Plus Low Tech" #mandatory
description='''
More Ores, better life, less ore generation'''